import './bootstrap';
import 'simplebar';
import 'simplebar/dist/simplebar.css';
import '../../public/assets/js/models/fluxschnell.js'
import '../../public/assets/js/switch.js'
import '../../public/assets/libs/preline/preline.js'
import '../../public/assets/libs/@popperjs/core/umd/popper.min.js'
import '../../public/assets/libs/@simonwep/pickr/pickr.es5.min.js'
import '../../public/assets/js/defaultmenu.js'
import '../../public/assets/js/sticky.js'
import '../../public/assets/js/chat.js'
import '../../public/assets/js/custom.js'
